# Generated by Django 3.2 on 2024-03-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_counseling'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staff',
        ),
    ]
