# Generated by Django 3.2 on 2024-03-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffId', models.CharField(max_length=10)),
                ('sName', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
